### ISSUE TITLE
Add member function for calculating the bounding box of the domain

### ISSUE THREAD

**Issue by ggorman** [ggorman/GeometryModel#12]
should look something like:

void bounding_box(double *bbox);

where 

double bbox[] = {min_x, max_x, min_y, max_y, min_z, max_z};

**Comment by vincepandolfo** [comment]
https://www.opencascade.com/doc/occt-6.9.0/refman/html/class_bnd___box.html

OpenCascade provides a class for bounding boxes. Should it return a Bnd_Box object or the list of values?

**Comment by ggorman** [comment]
Provide a member for both.

**Comment by vincepandolfo** [comment]
Done in PR #13
