### ISSUE TITLE
bounding_box appears to be broken

### ISSUE THREAD

**Issue by ggorman** [ggorman/GeometryModel#14]
$ cat ../tests/test_XDEReader.cpp 

```
#include "XDEReader.h"
#include "GeometryModel.h"

#include <iostream>

int main(int argc, char **args) {
    Handle(XCAFDoc_ShapeTool) iges_doc = readIGES("torous_n_box.igs");
    Handle(XCAFDoc_ShapeTool) step_doc = readSTEP("torous_n_box.stp");

    GeometryModel geom_model("torous_n_box.igs");

    double bbox[6];
    geom_model.bounding_box(bbox);

    return 0;
}
```

ggorman@ese-richter:~/projects/GeometryModel/build$ ./tests/test_XDEReader 
Total number of loaded entities : 110.
  **\*  Error on Record 46 (on 445 -> 10 % in File)  **\*  Ident #29
Complex Type incorrect : SOLID_ANGLE_UNIT / SI_UNIT ... 
  **\*  Error on Record 82 (on 445 -> 18 % in File)  **\*  Ident #64
Complex Type incorrect : NAMED_UNIT / LENGTH_UNIT ... 
Report : 3 unknown entities
Total number of loaded entities : 110.
terminate called after throwing an instance of 'Standard_ConstructionError'
Aborted

**Comment by vincepandolfo** [comment]
Solved in #15
