### ISSUE TITLE
Add tests for range of different file formats

### ISSUE THREAD

**Issue by ggorman** [ggorman/GeometryModel#3]
1. Add helper functions within tests directory.
2. Use OpenCascade to write out some simple shapes (e.g. a sphere within a box) using all the CAD export formats available to open cascade. This can be done using the python API.
3. Update the test case to cycle through all the formats, testing the distance member functions etc.

**Comment by vincepandolfo** [comment]
PR https://github.com/ggorman/GeometryModel/pull/5
