### ISSUE TITLE
Extend search for nearest point to retrieve the curvature at that point.

### ISSUE THREAD

**Issue by ggorman** [ggorman/GeometryModel#7]
Question? How does open cascade handle the situation where the nearest point is a geometric edge or corner.

**Comment by vincepandolfo** [comment]
In OpenCascade edges or corners are generally part of a surface so the curvature value we'd get is the curvature of the surface at that point. If it's part of multiple surfaces, then we'd have to pick one.

**Comment by vincepandolfo** [comment]
Done in PR https://github.com/ggorman/GeometryModel/pull/9
